############################
### FILE BROWSER RULESET ###
############################

windowrule = match:class org.gnome.Nautilus, tag +filebrowser

windowrule {
  name = files
  match:tag = filebrowser
  opacity = 0.90
  no_blur = true
}

