#####################
### GAMES RULESET ###
#####################

# game tags / store tags
windowrule = tag +game, match:class steam_app_\d+
windowrule = tag -game, match:title ^$|WeMod|P5XGame|Troubleshooter
windowrule = float true, match:class heroic, match:title negative:Heroic Games Launcher

# Steam
windowrule {
  name = steam
  match:class = steam
  match:title = Steam
  workspace = 4 silent
}

windowrule {
	name = steam-stuff
	match:class = steam
  match:title = ^(Launching*|Sign In*) negative:steam
	float = true
	center = true
	workspace = 1
}

windowrule {
  name = game
  match:tag = game

  workspace = 1
  content = game

  no_blur = true
  opacity = 1.0
  fullscreen = true
  float = false
}

windowrule {
  name = p5x
  match:class = steam_app_\d+
  match:title = P5XGame

  float = true
  center = true
  tag = -game
  workspace = 1
}

windowrule {
  name = wemod
  match:class = steam_app_\d+
  match:title = WeMod

  float = true
  center = true
  fullscreen = false
  size = (monitor_w*0.75) (monitor_h*0.75)
  tag = -game
  workspace = 5 silent
}

windowrule {
  name = troubleshooter
  match:class = Troubleshooter
  match:title = Troubleshooter

  float = true
  center = true

  workspace = 1
}
