########################
### SETTINGS RULESET ###
########################

windowrule = tag +settings, match:class nwg-displays|nwg-look
windowrule = tag +settings, match:class org.pulseaudio.pavucontrol
windowrule = tag +settings, match:class com.github.hyprmod

windowrule {
    name = settings
    match:tag = settings

    float = true
    center = true
    size = (monitor_w*0.75) (monitor_h*0.75)
}
