###################
### CUSTOM APPS ###
###################

### Nessessary Tools
$polkitagent = systemctl --user start hyprpolkitagent
$archUpdate = sleep 3 && arch-update --tray
$notificationCenter = swaync
$spotifyNotifications = systemctl --user start spotify-notify.service
$bar = waybar
$wallpaperEngine = awww-daemon

$terminal = kitty
$appmenu = $HOME/.config/rofi/launcher.sh "show drun" runner
$filemanager = nautilus
$browser = zen-browser
$discord = discord
$steam = steam
$music = spotify
$settings = $HOME/.config/bin/helper/hyprmod
$EDITOR = nvim

$themeSwitcher = $HOME/.config/bin/UI/themeMenu.sh
$wallpaperSelector = $HOME/.config/bin/UI/wallpaperSelector.sh
